### ISSUE TITLE
master is currently broken

### ISSUE THREAD

**Issue by dburov190** [climate-machine/CalibrateEmulateSample.jl#29]
`examples/GPR/main.jl` crashes with
```
ERROR: LoadError: LoadError: UndefVarError: Utilities not defined
```

**Comment by charleskawczynski** [comment]
This GPR test is working in `test/runtests.jl`. I just fixed a similar sounding issue with @bielim, she had to remove `CalibrateEmulateSample.jl` from here default environment to fix this.

**Comment by charleskawczynski** [comment]
**Assuming you're not developing in `.julia` directory**, I suggest you see if `CalibrateEmulateSample.jl` is in your `.julia` directory, if so, remove it. Then, go to your `CalibrateEmulateSample.jl` directory, and run `julia --project test/runtests.jl`.

**Comment by dburov190** [comment]
I don't have it in the `.julia` directory and it still fails even when I run it with `--project`, albeit with a different error:
```
ERROR: LoadError: ArgumentError: Package VersionParsing does not have Compat in its dependencies
```
I just did a fresh clone of the repository just in case.

Also, is it possible to run it without the `--project` flag? it used to work without it.

**Comment by charleskawczynski** [comment]
It's recommended to use the `--project` flag, since this instantiates the local project. Otherwise, it will grab the version in your default environment (`.julia/packages`, sorry I didn't include the extension last time) and, unless you run `julia ] dev .`, you'll have a frozen version of whatever you may have added to your default environment.

**Comment by dburov190** [comment]
Yeah but that's quite annoying; is there a way to have that as a default behavior? I don't care about the environments and all that, I just wanna hit `julia main.jl`, lean back and enjoy :D

Anyway, that's rather off-topic. `julia --project test/runtests.jl` still fails for me. Maybe there needs to be something installed in the `Project.toml`, like `VersionParsing`? Or update the julia itself? I'm running 1.1.

**Comment by charleskawczynski** [comment]
> Yeah but that's quite annoying; is there a way to have that as a default behavior?

I don't _think_ so, but I don't think this would be safe, since you should likely be aware of the [environment](https://julialang.github.io/Pkg.jl/stable/environments/) your running.

> Anyway, that's rather off-topic. julia --project test/runtests.jl still fails for me. Maybe there needs to be something installed in the Project.toml, like VersionParsing? Or update the julia itself? I'm running 1.1.

It could be that you need to update to the latest Julia version, what's the error you're getting?
